name: CI

on: push

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
        cache: 'pip'
    - name: update pip
      run: 
          pip install --upgrade pip
    - name : setuptools
      run:
          |
          pip uninstall setuptools -y
          pip install setuptools==20.1
    - name: install python packages
      run:
          |
          pip install -r requirements.txt
    - name: execute py script  
      run: 
        ipython trabalho_final.ipynb
