name: CI

on: push

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    - name: update pip
      run: 
          pip install --upgrade pip
    - name: install python packages
      run:
          pip install beautifulsoup4 requests google-auth google.colab google-cloud-storage elasticsearch
    - name: SQLAlchemy version
      run:
          pip install cloud-sql-python-connector["pymysql"] SQLAlchemy==2.0.7
    - name: execute py script  
      run: 
        ipython trabalho_final.ipynb
