name: CI

on: push

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    - name: install python packages
      run:
          pip install beautifulsoup4 requests
          pip install google-auth
          pip install google.colab
          pip install google-cloud-storage
          pip install cloud-sql-python-connector["pymysql"] SQLAlchemy==2.0.7
          pip install elasticsearch
    - name: execute py script  
      run: 
        ipython trabalho_final.ipynb
